#pragma once

namespace mce
{
	enum BlendTarget
	{
		BLEND_TARGET_DEST_COLOR,
		BLEND_TARGET_SOURCE_COLOR,
		BLEND_TARGET_ZERO,
		BLEND_TARGET_ONE,
		BLEND_TARGET_ONE_MINUS_DEST_COLOR,
		BLEND_TARGET_ONE_MINUS_SRC_COLOR,
		BLEND_TARGET_SOURCE_ALPHA,
		BLEND_TARGET_DEST_ALPHA,
		BLEND_TARGET_ONE_MINUS_SRC_ALPHA
	};
}
