#pragma once

namespace mce
{
    enum PrimitiveMode
    {
        PRIMITIVE_MODE_NONE,
        PRIMITIVE_MODE_QUAD_LIST,
        PRIMITIVE_MODE_TRIANGLE_LIST,
        PRIMITIVE_MODE_TRIANGLE_STRIP,
        PRIMITIVE_MODE_LINE_LIST,
        PRIMITIVE_MODE_LINE_STRIP,

        PRIMTIIVE_MODE_COUNT,
        PRIMITIVE_MODE_MIN = PRIMITIVE_MODE_NONE,
        PRIMITIVE_MODE_MAX = PRIMITIVE_MODE_LINE_STRIP
    };
}