#include "TextureHelperDXGI.hpp"
#include "common/Logger.hpp"

using namespace mce;

DXGI_FORMAT TextureHelperDXGI::DXGIFormatFromTextureFormat(TextureFormat textureFormat)
{
    switch (textureFormat)
    {
    case TEXTURE_FORMAT_R32G32B32A32_FLOAT:    return DXGI_FORMAT_R32G32B32A32_FLOAT;
    case TEXTURE_FORMAT_R16G16B16A16_FLOAT:    return DXGI_FORMAT_R16G16B16A16_FLOAT;
    case TEXTURE_FORMAT_R16G16B16A16_UNORM:    return DXGI_FORMAT_R16G16B16A16_UNORM;
    case TEXTURE_FORMAT_R32G32_FLOAT:          return DXGI_FORMAT_R32G32_FLOAT;
    case TEXTURE_FORMAT_R8G8B8A8_UNORM:        return DXGI_FORMAT_R8G8B8A8_UNORM;
    case TEXTURE_FORMAT_R8G8B8A8_UNORM_SRGB:   return DXGI_FORMAT_R8G8B8A8_UNORM_SRGB;
    case TEXTURE_FORMAT_R16G16_UNORM:          return DXGI_FORMAT_R16G16_UNORM;
    case TEXTURE_FORMAT_R16G16_UINT:           return DXGI_FORMAT_R16G16_UINT;
    case TEXTURE_FORMAT_D32_FLOAT:             return DXGI_FORMAT_D32_FLOAT;
    case TEXTURE_FORMAT_R32_FLOAT:             return DXGI_FORMAT_R32_FLOAT;
    case TEXTURE_FORMAT_R32_UINT:              return DXGI_FORMAT_R32_UINT;
    case TEXTURE_FORMAT_R24G8_TYPELESS:        return DXGI_FORMAT_R24G8_TYPELESS;
    case TEXTURE_FORMAT_D24_UNORM_S8_UINT:     return DXGI_FORMAT_D24_UNORM_S8_UINT;
    case TEXTURE_FORMAT_R24_UNORM_X8_TYPELESS: return DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
    case TEXTURE_FORMAT_R8_UNORM:              return DXGI_FORMAT_R8_UNORM;
    case TEXTURE_FORMAT_R8_UINT:               return DXGI_FORMAT_R8_UINT;
    case TEXTURE_FORMAT_A8_UNORM:              return DXGI_FORMAT_A8_UNORM;
    case TEXTURE_FORMAT_BC3_UNORM:             return DXGI_FORMAT_BC3_UNORM;
    case TEXTURE_FORMAT_B8G8R8A8_UNORM:        return DXGI_FORMAT_B8G8R8A8_UNORM;
    case TEXTURE_FORMAT_B8G8R8A8_UNORM_SRGB:   return DXGI_FORMAT_B8G8R8A8_UNORM_SRGB;
    case TEXTURE_FORMAT_BC7_UNORM:             return DXGI_FORMAT_BC7_UNORM;
    default:
        LOG_W("Unknown textureFormat: %d", textureFormat);
        return DXGI_FORMAT_UNKNOWN;
    }
}

TextureFormat TextureHelperDXGI::TextureFormatFromDXGIFormat(DXGI_FORMAT dxgiFormat)
{
    switch (dxgiFormat)
    {
    case DXGI_FORMAT_R16G16B16A16_FLOAT:    return TEXTURE_FORMAT_R16G16B16A16_FLOAT;
    case DXGI_FORMAT_R16G16B16A16_UNORM:    return TEXTURE_FORMAT_R16G16B16A16_UNORM;
    case DXGI_FORMAT_R8G8B8A8_UNORM:        return TEXTURE_FORMAT_R8G8B8A8_UNORM;
    case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:   return TEXTURE_FORMAT_R8G8B8A8_UNORM_SRGB;
    case DXGI_FORMAT_R16G16_UNORM:          return TEXTURE_FORMAT_R16G16_UNORM;
    case DXGI_FORMAT_R32_FLOAT:             return TEXTURE_FORMAT_R32_FLOAT;
    case DXGI_FORMAT_R32_UINT:              return TEXTURE_FORMAT_R32_UINT;
    case DXGI_FORMAT_R24_UNORM_X8_TYPELESS: return TEXTURE_FORMAT_R24_UNORM_X8_TYPELESS;
    case DXGI_FORMAT_R8_UNORM:              return TEXTURE_FORMAT_R8_UNORM;
    case DXGI_FORMAT_R8_UINT:               return TEXTURE_FORMAT_R8_UINT;
    case DXGI_FORMAT_A8_UNORM:              return TEXTURE_FORMAT_A8_UNORM;
    case DXGI_FORMAT_BC3_UNORM:             return TEXTURE_FORMAT_BC3_UNORM;
    case DXGI_FORMAT_B8G8R8A8_UNORM:        return TEXTURE_FORMAT_B8G8R8A8_UNORM;
    case DXGI_FORMAT_BC7_UNORM:             return TEXTURE_FORMAT_BC7_UNORM;
    default:
        LOG_W("Unknown dxgiFormat: %d", dxgiFormat);
        return TEXTURE_FORMAT_UNKNOWN;
    }
}