/********************************************************************
	Minecraft: Pocket Edition - Decompilation Project
	Copyright (C) 2023 iProgramInCpp
	
	The following code is licensed under the BSD 1 clause license.
	SPDX-License-Identifier: BSD-1-Clause
 ********************************************************************/

#pragma once

#include "RakNetVersion.h"
#include "RakNetTypes.h"
#include "BitStream.h"
#include "MessageIdentifiers.h"

#define NETWORK_PROTOCOL_VERSION_MIN 6 // the packet IDs changed completely between 2 thru 6
//#define NETWORK_PROTOCOL_VERSION 2   // 0.1.0 (actual client crashes with unrecognized tiles)
//#define NETWORK_PROTOCOL_VERSION 3   // 0.2.0 (actual client crashes with unrecognized entities)
//#define NETWORK_PROTOCOL_VERSION 4   // 0.3.0
//#define NETWORK_PROTOCOL_VERSION 5   // 0.3.2
#define NETWORK_PROTOCOL_VERSION 6	   // 0.3.3
//#define NETWORK_PROTOCOL_VERSION 7   // 0.4.0
//#define NETWORK_PROTOCOL_VERSION 29  // 0.12.1

class NetEventCallback;
class Level;
class LevelChunk;

// RakNet requires this to be cast to an "unsigned char" before being written to the BitStream
enum MinecraftPacketIds
#ifndef USE_OLD_CPP
: uint8_t // this is compiled as a 32-bit integer in C++03 and earlier, and we obviously CANNOT afford a 24-bit inconsitency.
// TODO: WritePacketType function that casts this down to a uint8_t / an unsigned 8-bit integer?
#endif
{
#if NETWORK_PROTOCOL_VERSION <= 2

#if RAKNET_PROTOCOL_VERSION != 4
#error RAKNET_PROTOCOL_VERSION must be 4
#endif

	PACKET_LOGIN = ID_USER_PACKET_ENUM,
	PACKET_MESSAGE,
	PACKET_START_GAME,
	PACKET_ADD_PLAYER,
	PACKET_REMOVE_ENTITY,
	PACKET_MOVE_PLAYER,
	PACKET_PLACE_BLOCK,
	PACKET_REMOVE_BLOCK,
	PACKET_UPDATE_BLOCK,
	PACKET_REQUEST_CHUNK,
	PACKET_CHUNK_DATA,
	PACKET_PLAYER_EQUIPMENT,

	PACKET_LEVEL_DATA = 200,

	// Used in future protocol versions
	PACKET_LOGIN_STATUS,
	PACKET_READY,
	PACKET_SET_TIME,
	PACKET_ADD_MOB,
	PACKET_REMOVE_PLAYER,
	PACKET_ADD_ITEM_ENTITY,
	PACKET_TAKE_ITEM_ENTITY,
	PACKET_MOVE_ENTITY,
	PACKET_MOVE_ENTITY_POS,
	PACKET_MOVE_ENTITY_ROT,
	PACKET_MOVE_ENTITY_POS_ROT,
	PACKET_EXPLODE,
	PACKET_LEVEL_EVENT,
	PACKET_ENTITY_EVENT,
	PACKET_INTERACT,
	PACKET_USE_ITEM,
	PACKET_SET_ENTITY_DATA,
	PACKET_SET_HEALTH,
	PACKET_ANIMATE,
	PACKET_RESPAWN

#elif NETWORK_PROTOCOL_VERSION <= 3

#if RAKNET_PROTOCOL_VERSION != 4
#error RAKNET_PROTOCOL_VERSION must be 4
#endif

	PACKET_LOGIN = ID_USER_PACKET_ENUM,
	PACKET_LOGIN_STATUS,
	PACKET_READY,
	PACKET_MESSAGE,
	PACKET_SET_TIME,
	PACKET_START_GAME,
	PACKET_ADD_MOB,
	PACKET_ADD_PLAYER,
	PACKET_REMOVE_PLAYER,
	PACKET_ADD_ENTITY = 143,
	PACKET_REMOVE_ENTITY,
	PACKET_ADD_ITEM_ENTITY,
	PACKET_TAKE_ITEM_ENTITY,
	PACKET_MOVE_ENTITY,
	PACKET_MOVE_ENTITY_POS,
	PACKET_MOVE_ENTITY_ROT,
	PACKET_MOVE_ENTITY_POS_ROT,
	PACKET_MOVE_PLAYER,
	PACKET_PLACE_BLOCK,
	PACKET_REMOVE_BLOCK,
	PACKET_UPDATE_BLOCK,
	PACKET_EXPLODE,
	PACKET_LEVEL_EVENT,
	PACKET_ENTITY_EVENT,
	PACKET_REQUEST_CHUNK,
	PACKET_CHUNK_DATA,
	PACKET_PLAYER_EQUIPMENT,
	PACKET_INTERACT,
	PACKET_USE_ITEM,
	PACKET_SET_ENTITY_DATA,
	PACKET_SET_HEALTH,
	PACKET_ANIMATE,
	PACKET_RESPAWN,

	PACKET_LEVEL_DATA = 200

#elif NETWORK_PROTOCOL_VERSION <= 4

#if RAKNET_PROTOCOL_VERSION != 5
#error RAKNET_PROTOCOL_VERSION must be 5
#endif

	PACKET_LOGIN = ID_USER_PACKET_ENUM - 4, // really Mojang?
	PACKET_LOGIN_STATUS,
	PACKET_READY,
	PACKET_MESSAGE,
	PACKET_SET_TIME,
	PACKET_START_GAME,
	PACKET_ADD_MOB,
	PACKET_ADD_PLAYER,
	PACKET_REMOVE_PLAYER,
	PACKET_ADD_ENTITY = 139,
	PACKET_REMOVE_ENTITY,
	PACKET_ADD_ITEM_ENTITY,
	PACKET_TAKE_ITEM_ENTITY,
	PACKET_MOVE_ENTITY,
	PACKET_MOVE_ENTITY_POS,
	PACKET_MOVE_ENTITY_ROT,
	PACKET_MOVE_ENTITY_POS_ROT,
	PACKET_MOVE_PLAYER,
	PACKET_PLACE_BLOCK,
	PACKET_REMOVE_BLOCK,
	PACKET_UPDATE_BLOCK,
	PACKET_EXPLODE,
	PACKET_LEVEL_EVENT,
	PACKET_ENTITY_EVENT,
	PACKET_REQUEST_CHUNK,
	PACKET_CHUNK_DATA,
	PACKET_PLAYER_EQUIPMENT,
	PACKET_INTERACT,
	PACKET_USE_ITEM,
	PACKET_SET_ENTITY_DATA,
	PACKET_SET_HEALTH,
	PACKET_ANIMATE,
	PACKET_RESPAWN,
	PACKET_SEND_INVENTORY,
	PACKET_DROP_ITEM,

	PACKET_LEVEL_DATA = 200

#elif NETWORK_PROTOCOL_VERSION <= 5

#if RAKNET_PROTOCOL_VERSION != 5
#error RAKNET_PROTOCOL_VERSION must be 5
#endif

	PACKET_LOGIN = ID_USER_PACKET_ENUM - 4, // really Mojang?
	PACKET_LOGIN_STATUS,
	PACKET_READY,
	PACKET_MESSAGE,
	PACKET_SET_TIME,
	PACKET_START_GAME,
	PACKET_ADD_MOB,
	PACKET_ADD_PLAYER,
	PACKET_REMOVE_PLAYER,
	PACKET_ADD_ENTITY = 139,
	PACKET_REMOVE_ENTITY,
	PACKET_ADD_ITEM_ENTITY,
	PACKET_TAKE_ITEM_ENTITY,
	PACKET_MOVE_ENTITY,
	PACKET_MOVE_ENTITY_POS,
	PACKET_MOVE_ENTITY_ROT,
	PACKET_MOVE_ENTITY_POS_ROT,
	PACKET_MOVE_PLAYER,
	PACKET_PLACE_BLOCK,
	PACKET_REMOVE_BLOCK,
	PACKET_UPDATE_BLOCK,
	PACKET_EXPLODE,
	PACKET_LEVEL_EVENT,
	PACKET_TILE_EVENT,
	PACKET_ENTITY_EVENT,
	PACKET_REQUEST_CHUNK,
	PACKET_CHUNK_DATA,
	PACKET_PLAYER_EQUIPMENT,
	PACKET_INTERACT,
	PACKET_USE_ITEM,
	PACKET_SET_ENTITY_DATA,
	PACKET_SET_ENTITY_MOTION,
	PACKET_SET_HEALTH,
	PACKET_ANIMATE,
	PACKET_RESPAWN,
	PACKET_SEND_INVENTORY,
	PACKET_DROP_ITEM,
	PACKET_CONTAINER_OPEN,
	PACKET_CONTAINER_CLOSE,
	PACKET_CONTAINER_SET_SLOT,
	PACKET_CONTAINER_SET_DATA,
	PACKET_CONTAINER_SET_CONTENT,
	PACKET_CONTAINER_ACK, // Unused in PE

	PACKET_LEVEL_DATA = 200

#else

#if RAKNET_PROTOCOL_VERSION != 5
#error RAKNET_PROTOCOL_VERSION must be 5
#endif

	PACKET_LOGIN = ID_USER_PACKET_ENUM - 4, // really Mojang?
	PACKET_LOGIN_STATUS,
	PACKET_READY,
	PACKET_MESSAGE,
	PACKET_SET_TIME,
	PACKET_START_GAME,
	PACKET_ADD_MOB,
	PACKET_ADD_PLAYER,
	PACKET_REMOVE_PLAYER,
	PACKET_ADD_ENTITY = 140,
	PACKET_REMOVE_ENTITY,
	PACKET_ADD_ITEM_ENTITY,
	PACKET_TAKE_ITEM_ENTITY,
	PACKET_MOVE_ENTITY,
	PACKET_MOVE_ENTITY_POS,
	PACKET_MOVE_ENTITY_ROT,
	PACKET_MOVE_ENTITY_POS_ROT,
	PACKET_MOVE_PLAYER,
	PACKET_PLACE_BLOCK,
	PACKET_REMOVE_BLOCK,
	PACKET_UPDATE_BLOCK,
	PACKET_EXPLODE,
	PACKET_LEVEL_EVENT,
	PACKET_TILE_EVENT,
	PACKET_ENTITY_EVENT,
	PACKET_REQUEST_CHUNK,
	PACKET_CHUNK_DATA,
	PACKET_PLAYER_EQUIPMENT,
	PACKET_INTERACT,
	PACKET_USE_ITEM,
	PACKET_PLAYER_ACTION,
	PACKET_SET_ENTITY_DATA,
	PACKET_SET_ENTITY_MOTION,
	PACKET_SET_HEALTH,
	PACKET_ANIMATE,
	PACKET_RESPAWN,
	PACKET_SEND_INVENTORY,
	PACKET_DROP_ITEM,
	PACKET_CONTAINER_OPEN,
	PACKET_CONTAINER_CLOSE,
	PACKET_CONTAINER_SET_SLOT,
	PACKET_CONTAINER_SET_DATA,
	PACKET_CONTAINER_SET_CONTENT,
	PACKET_CONTAINER_ACK, // Unused in PE
	PACKET_CHAT,

	PACKET_LEVEL_DATA = 200

#endif
};

class Packet
{
public:
	virtual ~Packet() {}
	virtual void write(RakNet::BitStream&) = 0;
	virtual void read(RakNet::BitStream&) = 0;
	virtual void handle(const RakNet::RakNetGUID&, NetEventCallback&) = 0;
};
