SOUND(step, cloth, 1)
SOUND(step, cloth, 2)
SOUND(step, cloth, 3)
SOUND(step, cloth, 4)

SOUND(step, grass, 1)
SOUND(step, grass, 2)
SOUND(step, grass, 3)
SOUND(step, grass, 4)

SOUND(step, gravel, 1)
SOUND(step, gravel, 2)
SOUND(step, gravel, 3)
SOUND(step, gravel, 4)

SOUND(step, sand, 1)
SOUND(step, sand, 2)
SOUND(step, sand, 3)
SOUND(step, sand, 4)

SOUND(step, stone, 1)
SOUND(step, stone, 2)
SOUND(step, stone, 3)
SOUND(step, stone, 4)

SOUND(step, wood, 1)
SOUND(step, wood, 2)
SOUND(step, wood, 3)
SOUND(step, wood, 4)

SOUND(random, bow, )
SOUND(random, click, )
SOUND(random, door_close, )
SOUND(random, door_open, )
SOUND(random, drr, )
SOUND(random, explode, )
SOUND(random, fizz, )
SOUND(random, fuse, )
SOUND(random, hurt, )
SOUND(random, pop, )
SOUND(random, splash, )

SOUND(fire, fire, )

SOUND(damage, fallbig, 1)
SOUND(damage, fallbig, 2)

SOUND(damage, fallsmall, )

SOUND(mob, chicken, 2)
SOUND(mob, chicken, 3)
SOUND(mob, chickenhurt, 1)
SOUND(mob, chickenhurt, 2)

SOUND(mob, cow, 1)
SOUND(mob, cow, 2)
SOUND(mob, cow, 3)
SOUND(mob, cow, 4)
SOUND(mob, cowhurt, 1)
SOUND(mob, cowhurt, 2)
SOUND(mob, cowhurt, 3)

SOUND(mob, creeper, 1)
SOUND(mob, creeper, 2)
SOUND(mob, creeper, 3)
SOUND(mob, creeper, 4)
SOUND(mob, creeperdeath, )

SOUND(mob, pig, 1)
SOUND(mob, pig, 2)
SOUND(mob, pig, 3)
SOUND(mob, pigdeath, )

SOUND(mob, sheep, 1)
SOUND(mob, sheep, 2)
SOUND(mob, sheep, 3)

SOUND(mob, skeleton, 1)
SOUND(mob, skeleton, 2)
SOUND(mob, skeleton, 3)
SOUND(mob, skeletonhurt, 1)
SOUND(mob, skeletonhurt, 2)
SOUND(mob, skeletonhurt, 3)
SOUND(mob, skeletonhurt, 4)
SOUND(mob, skeletondeath, )

SOUND(mob, spider, 1)
SOUND(mob, spider, 2)
SOUND(mob, spider, 3)
SOUND(mob, spider, 4)
SOUND(mob, spiderdeath, )

SOUND(mob, zombie, 1)
SOUND(mob, zombie, 2)
SOUND(mob, zombie, 3)
SOUND(mob, zombiehurt, 1)
SOUND(mob, zombiehurt, 2)
SOUND(mob, zombiedeath, )
