SOUND_NUM(step, cloth, 1)
SOUND_NUM(step, cloth, 2)
SOUND_NUM(step, cloth, 3)
SOUND_NUM(step, cloth, 4)

SOUND_NUM(step, grass, 1)
SOUND_NUM(step, grass, 2)
SOUND_NUM(step, grass, 3)
SOUND_NUM(step, grass, 4)

SOUND_NUM(step, gravel, 1)
SOUND_NUM(step, gravel, 2)
SOUND_NUM(step, gravel, 3)
SOUND_NUM(step, gravel, 4)

SOUND_NUM(step, sand, 1)
SOUND_NUM(step, sand, 2)
SOUND_NUM(step, sand, 3)
SOUND_NUM(step, sand, 4)

SOUND_NUM(step, stone, 1)
SOUND_NUM(step, stone, 2)
SOUND_NUM(step, stone, 3)
SOUND_NUM(step, stone, 4)

SOUND_NUM(step, wood, 1)
SOUND_NUM(step, wood, 2)
SOUND_NUM(step, wood, 3)
SOUND_NUM(step, wood, 4)

SOUND(random, bow)
SOUND(random, click)
SOUND(random, door_close)
SOUND(random, door_open)
SOUND(random, drr)
SOUND(random, explode)
SOUND(random, fizz)
SOUND(random, fuse)
SOUND(random, hurt)
SOUND(random, pop)
SOUND(random, splash)

SOUND(fire, fire)

SOUND_NUM(damage, fallbig, 1)
SOUND_NUM(damage, fallbig, 2)

SOUND(damage, fallsmall)

SOUND_NUM(mob, chicken, 2)
SOUND_NUM(mob, chicken, 3)
SOUND_NUM(mob, chickenhurt, 1)
SOUND_NUM(mob, chickenhurt, 2)

SOUND_NUM(mob, cow, 1)
SOUND_NUM(mob, cow, 2)
SOUND_NUM(mob, cow, 3)
SOUND_NUM(mob, cow, 4)
SOUND_NUM(mob, cowhurt, 1)
SOUND_NUM(mob, cowhurt, 2)
SOUND_NUM(mob, cowhurt, 3)

SOUND_NUM(mob, creeper, 1)
SOUND_NUM(mob, creeper, 2)
SOUND_NUM(mob, creeper, 3)
SOUND_NUM(mob, creeper, 4)
SOUND(mob, creeperdeath)

SOUND_NUM(mob, pig, 1)
SOUND_NUM(mob, pig, 2)
SOUND_NUM(mob, pig, 3)
SOUND(mob, pigdeath)

SOUND_NUM(mob, sheep, 1)
SOUND_NUM(mob, sheep, 2)
SOUND_NUM(mob, sheep, 3)

SOUND_NUM(mob, skeleton, 1)
SOUND_NUM(mob, skeleton, 2)
SOUND_NUM(mob, skeleton, 3)
SOUND_NUM(mob, skeletonhurt, 1)
SOUND_NUM(mob, skeletonhurt, 2)
SOUND_NUM(mob, skeletonhurt, 3)
SOUND_NUM(mob, skeletonhurt, 4)
SOUND(mob, skeletondeath)

SOUND_NUM(mob, spider, 1)
SOUND_NUM(mob, spider, 2)
SOUND_NUM(mob, spider, 3)
SOUND_NUM(mob, spider, 4)
SOUND(mob, spiderdeath)

SOUND_NUM(mob, zombie, 1)
SOUND_NUM(mob, zombie, 2)
SOUND_NUM(mob, zombie, 3)
SOUND_NUM(mob, zombiehurt, 1)
SOUND_NUM(mob, zombiehurt, 2)
SOUND(mob, zombiedeath)
